module.exports = {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      href: '/changelog',
      label: '🔄 Changelog',
    },
    {
      type: 'link',
      href: '/license',
      label: '📃 License',
    },
    {
      type: 'link',
      label: '💬 Chat with us on Slack',
      href: 'https://phpchat.co/?ref=telegram-bot-sdk-docs',
    },
    {
      type: 'link',
      label: '🐘 Chat with us on Telegram',
      href: 'https://t.me/PHPChatCo',
    },
  ],
};
